language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
env:
  global:
    secure: C6LoesT2+UBKDir4BrVZrB5u9huhZrIs4QpSVvUN8JrUa5R8xmWLCuRD4VLEn4qP5zToqUp0oxxFstg+0RswPPytQ8GdZ6V+iZWD9V8o2rEhPbE4rjV3VB1z4vqEolgSVkaZUZICo+B4f13XjFhpq0yRhYNJJ3EuVWwZ5kzm5swB4+qN9Hz9FdvUWiwu7/tnpfG7MeK2/rfYxNnveL/9b2VaXHEuVy/AXUvxngH+4Nabw5F4LVKHnbak5XTcvHldfgdX5pnQHw3MZ/NpYmo8sFTUxw4IUMjOzrATwSDQ67RRL/k8uVmB3XlBGJ24vt9wqZpIML3ie6RIj1LL9qrhYCZLKe6FzX7ELFSTlTIaAwqzwVnj+Z0dJJOjUS/qmAK5/mfuchiyASTlIEuWuG7ovdZMpHQlOI7Z/FBj9iZEPrGCWh97wgjgve64oXncWFn1VRNhYhyve1+0WR9YqYYmimamzX2eNGhRcMjH9j2P++ghjXkDqplfD7wcPlTH6ZvhHw3w7ZNLHhUOc8kugwlVVnBqfek///zkiNHUqxEnGzVIpJn6BMMHqnT41NO9Xcuu4ul4S1OJ2TY37MSOGtSr7+9zZHz6k8iVjMJVjnPmmxmjDw7KQsmUovrcPgm8+vY7YSADR+zQZG/VB+qnIDatx5Bhn0A/SK55mJ+2TUKVY7w=
